### ISSUE TITLE
Sourcetype cannot be changed in Splunk Addon for Microsoft Cloud Services

### ISSUE THREAD

**Issue by EricMooreHays** [splunk/TA-microsoft-365-defender-advanced-hunting-add-on#12]
We've set up the Microsoft Cloud Services app to read the defender alerts from Event hub as per the instructions, but the option to change the sourcetype is not possible. The app only offers a dropdrown list of 4: we chose mscs:azure:eventhub. 

The docs then also refer to the Microsoft Security App, but that appears to use the now deprecated defender API. 

We've managed to adapt this app to pick the events up by changing eventtypes.conf to pick up the actual source pulled from the event hub (source = [eventhub://xxx-defender-events.servicebus.windows.net/xxx-defender-events;]) and most of the eventtypes and tags are fine, but we can't work out where the additional sourcetypes in the eventtypes.conf come from 

[ms_defender_advanced_hunting_malware_summary]
search = sourcetype="defender:advancedhunting:malware"
#tags malware attack

[ms_defender_advanced_hunting_email_summary]
search = sourcetype="defender:advancedhunting:email"
#tags email delivery

[ms_defender_advanced_hunting_email_summary_content]
search = sourcetype="defender:advancedhunting:email" file_name=*

Can you please guide us to finding the transforms that set these sourcetypes when the data is being pulled via the eventhub. 
Thank You

**Comment by inspired** [comment]
Hi,

I'll check with the app developers of the Microsoft Cloud Services Add-on why free text fields aren't available to use.

Regarding the additional sourcetypes these are populated by Summary Indexing saved searches bundled with the app. Look in savedsearches.conf. This is also called out in the README

**Comment by inspired** [comment]
![image](https://user-images.githubusercontent.com/52004/226591522-8279cf32-6abc-41f2-8e7f-b87c4ca24fc6.png)

This shows the problem you're facing, for internal reference.

**Comment by inspired** [comment]
I've spoken to product management and got the following replies:

- Version 5.0.0 of the [Splunk Add-on for Microsoft Cloud Services](https://splunkbase.splunk.com/app/3110) will support custom sourcetypes. No ETA yet, but soon
In the meantime, if you're on Splunk Enterprise, you can manually change the sourcetype in inputs.conf

- [Splunk Add-on for Microsoft Security](https://splunkbase.splunk.com/app/6207) version 2.0.0 will support the new Graph API. No ETA yet, but soon

**Comment by inspired** [comment]
Splunk Add-on for Microsoft Cloud Services version 5.0.0 has been released
